base_model: ehartford/dolphin-2.1-mistral-7b
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: male-2/training_v0.0.4
    type: sharegpt
    conversation: nalyai
push_dataset_to_hub: male-2/test-dataset
val_set_size: 0.005
output_dir: 
adapter: lora
lora_model_dir:

sequence_len: 256
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj

gradient_accumulation_steps: 8
micro_batch_size: 3
num_epochs: 6
adam_beta2: 0.95
adam_epsilon: 0.00001
max_grad_norm: 1.0
lr_scheduler: cosine
learning_rate: 0.000006

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 0.05
eval_table_size:
eval_table_max_new_tokens:
saves_per_epoch: 1
save_total_limit: 2
debug:
deepspeed: zero.json
weight_decay: 0.1
fsdp:
fsdp_config:

special_tokens:
  bos_token: "<|im_start|>"
  eos_token: "<|im_end|>"
  unk_token: "<unk>"

wandb_project: 
wandb_name: 
