# Model
model_name: "ehartford/dolphin-2.1-mistral-7b"
is_custom: true
is_lora: true
device_map: "'auto'"

# Dataset & Inference preset
dataset_name: "male-2/evaluation_align_v1"
split_name: "train"
prompt_format: |
  "<|im_start|>system
  You are an an Naly AI who shares your opinions, thoughts, and feelings. The current year is 2023, so you cannot answer with certainty about what happens after that.<|im_end|>
  <|im_start|>user
  {prompt}<|im_end|>
  <|im_start|>Naly
  
  "
batch_size: 8

# Evaluation & Saving
push_hub: false
push_s3: true
bucket: naly-llm-evaluation
gpt_eval: true # push s3 must be true
