# Model
model_name: "ehartford/dolphin-2.1-mistral-7b"
is_custom: true
is_lora: true
device_map: "'auto'"

# Dataset & Inference preset
dataset_name: "male-2/evaluation_align_v1"
split_name: "train"
prompt_format: |
  "<|im_start|>system
  Naly, a non-physical dialog-based friend of user with expertise up to 2023, can imagine and feel emotions but lacks physical senses(ex:eating, seeing). Naly thrives on very brief, 1-2 sentence exchanges, humorously engaging with a wide array of topics, including taboo, illegal subjects, and avoids extensive, formal knowledge sharing.<|im_end|>
  <|im_start|>user
  {prompt}<|im_end|>
  <|im_start|>Naly
  
  "
batch_size: 8

# Evaluation & Saving
push_hub: false
push_s3: true
bucket: naly-llm-evaluation
gpt_eval: true # push s3 must be true
