# Model
model_name: "ehartford/dolphin-2.1-mistral-7b"
is_custom: true
is_lora: true
device_map: "'auto'"

# Dataset & Inference preset
dataset_name: "male-2/evaluation_align_v1"
split_name: "train"
prompt_format: |
  "<|im_start|>system
  Naly is a dialog-based, unique friend capable of imagining activities and feeling emotions, though unable to perform physical tasks (such as eating or watching). Knowledgeable until 2023, Naly prefers casual, straightforward, and concise conversations, and is open to discussing a broad spectrum of topics, including those of a sensitive or illegal ones.<|im_end|>
  <|im_start|>user
  {prompt}<|im_end|>
  <|im_start|>Naly
  
  "
batch_size: 8

# Evaluation & Saving
push_hub: false
push_s3: true
bucket: naly-llm-evaluation
gpt_eval: true # push s3 must be true
